"""
Heatmap Visualization: Generate visual representations of player throw patterns.
Supports multiple visualization formats (HTML, JSON, ASCII).
"""

from typing import Dict, List, Tuple, Optional
from dataclasses import dataclass
import json


@dataclass
class HeatmapData:
    """Data structure for heatmap visualization."""
    segment: int
    hits: int  # Total hits on this segment
    singles: int
    doubles: int
    triples: int
    total_score: int
    intensity: float  # 0.0-1.0 for color intensity
    consistency: float  # 0.0-1.0 for throw consistency


class HeatmapVisualizer:
    """Generates visual heatmaps of dartboard throw patterns."""
    
    # Dartboard segment order (clockwise from top)
    DARTBOARD_ORDER = [20, 1, 18, 4, 13, 6, 10, 15, 2, 17, 3, 19, 7, 16, 8, 11, 14, 9, 12, 5, 25]
    
    def __init__(self, player_name: str, heatmap_data: Dict[int, Dict]):
        self.player_name = player_name
        self.heatmap_data = heatmap_data
    
    def generate_html(self) -> str:
        """Generate an interactive HTML heatmap."""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Dartboard Heatmap - {self.player_name}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background: #1a1a1a;
            color: #fff;
            padding: 20px;
        }}
        .container {{
            max-width: 1000px;
            margin: 0 auto;
        }}
        h1 {{
            text-align: center;
            color: #00ff00;
        }}
        .dartboard {{
            display: grid;
            grid-template-columns: repeat(6, 1fr);
            gap: 10px;
            margin: 20px 0;
        }}
        .segment {{
            aspect-ratio: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            border-radius: 10px;
            font-weight: bold;
            cursor: pointer;
            transition: all 0.3s;
            position: relative;
        }}
        .segment:hover {{
            transform: scale(1.1);
        }}
        .segment-label {{
            font-size: 24px;
            z-index: 2;
        }}
        .segment-info {{
            position: absolute;
            bottom: 5px;
            right: 5px;
            font-size: 12px;
            background: rgba(0,0,0,0.7);
            padding: 3px 6px;
            border-radius: 3px;
        }}
        .stats {{
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-top: 30px;
        }}
        .stat-box {{
            background: #222;
            padding: 15px;
            border-radius: 10px;
            border-left: 4px solid #00ff00;
        }}
        .stat-label {{
            color: #888;
            font-size: 12px;
            text-transform: uppercase;
        }}
        .stat-value {{
            font-size: 28px;
            font-weight: bold;
            color: #00ff00;
        }}
        .legend {{
            margin-top: 30px;
            padding: 15px;
            background: #222;
            border-radius: 10px;
        }}
        .legend-item {{
            display: inline-block;
            margin-right: 20px;
            margin-bottom: 10px;
        }}
        .legend-color {{
            display: inline-block;
            width: 20px;
            height: 20px;
            border-radius: 3px;
            margin-right: 5px;
            vertical-align: middle;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🎯 Dartboard Heatmap: {self.player_name}</h1>
        
        <div class="dartboard" id="dartboard">
            <!-- Generated by JavaScript -->
        </div>
        
        <div class="stats">
            <div class="stat-box">
                <div class="stat-label">Total Hits</div>
                <div class="stat-value" id="total-hits">0</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Favorite Segment</div>
                <div class="stat-value" id="favorite-segment">--</div>
            </div>
            <div class="stat-box">
                <div class="stat-label">Average Score</div>
                <div class="stat-value" id="avg-score">0</div>
            </div>
        </div>
        
        <div class="legend">
            <div class="legend-item">
                <span class="legend-color" style="background: #0a0a0a;"></span>
                <span>No hits</span>
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #ff6600;"></span>
                <span>Low activity</span>
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #ffaa00;"></span>
                <span>Medium activity</span>
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #00ff00;"></span>
                <span>High activity</span>
            </div>
            <div class="legend-item">
                <span class="legend-color" style="background: #00ffff;"></span>
                <span>Very high activity</span>
            </div>
        </div>
    </div>
    
    <script>
        const heatmapData = {json.dumps(self.heatmap_data)};
        
        function getColor(intensity) {{
            if (intensity === 0) return '#0a0a0a';
            if (intensity < 0.2) return '#ff6600';
            if (intensity < 0.4) return '#ffaa00';
            if (intensity < 0.7) return '#ffff00';
            if (intensity < 0.9) return '#00ff00';
            return '#00ffff';
        }}
        
        function initDartboard() {{
            const dartboard = document.getElementById('dartboard');
            const segments = [20, 1, 18, 4, 13, 6, 10, 15, 2, 17, 3, 19, 7, 16, 8, 11, 14, 9, 12, 5, 25];
            
            let totalHits = 0;
            let maxHits = 0;
            let favoriteSegment = 0;
            let totalScore = 0;
            
            segments.forEach(seg => {{
                const data = heatmapData[seg] || {{}};
                const hits = data.total_hits || 0;
                const intensity = data.intensity || 0;
                
                totalHits += hits;
                totalScore += data.total_score || 0;
                
                if (hits > maxHits) {{
                    maxHits = hits;
                    favoriteSegment = seg;
                }}
                
                const div = document.createElement('div');
                div.className = 'segment';
                div.style.backgroundColor = getColor(intensity);
                div.innerHTML = `
                    <span class="segment-label">${{seg === 25 ? 'B' : seg}}</span>
                    <div class="segment-info">${{hits}}</div>
                `;
                div.title = `Segment ${{seg}}: ${{hits}} hits, ${{data.total_score || 0}} points`;
                dartboard.appendChild(div);
            }});
            
            document.getElementById('total-hits').textContent = totalHits;
            document.getElementById('favorite-segment').textContent = favoriteSegment === 25 ? 'Bull' : favoriteSegment;
            document.getElementById('avg-score').textContent = totalHits > 0 ? Math.round(totalScore / totalHits) : 0;
        }}
        
        initDartboard();
    </script>
</body>
</html>
        """
        return html
    
    def generate_ascii(self) -> str:
        """Generate an ASCII representation of the heatmap."""
        ascii_art = f"\n🎯 DARTBOARD HEATMAP: {self.player_name}\n"
        ascii_art += "=" * 50 + "\n\n"
        
        # Create ASCII dartboard representation
        ascii_art += "        20\n"
        ascii_art += "    1       18\n"
        ascii_art += "  4           13\n"
        ascii_art += "6               10\n"
        ascii_art += "15               2\n"
        ascii_art += "17               3\n"
        ascii_art += "19               7\n"
        ascii_art += "16               8\n"
        ascii_art += "11               14\n"
        ascii_art += "9                12\n"
        ascii_art += "        5\n"
        ascii_art += "       BULL\n\n"
        
        # Statistics
        total_hits = sum(d.get("total_hits", 0) for d in self.heatmap_data.values())
        total_score = sum(d.get("total_score", 0) for d in self.heatmap_data.values())
        
        ascii_art += "STATISTICS:\n"
        ascii_art += f"  Total Hits: {total_hits}\n"
        ascii_art += f"  Total Score: {total_score}\n"
        ascii_art += f"  Average: {total_score / total_hits if total_hits > 0 else 0:.1f}\n\n"
        
        # Top segments
        sorted_segs = sorted(
            [(seg, d.get("total_hits", 0)) for seg, d in self.heatmap_data.items()],
            key=lambda x: x[1],
            reverse=True
        )
        
        ascii_art += "TOP SEGMENTS:\n"
        for i, (seg, hits) in enumerate(sorted_segs[:5], 1):
            seg_label = "Bull" if seg == 25 else str(seg)
            ascii_art += f"  {i}. Segment {seg_label}: {hits} hits\n"
        
        return ascii_art
    
    def generate_json(self) -> str:
        """Generate JSON representation of the heatmap."""
        return json.dumps({
            "player": self.player_name,
            "heatmap": self.heatmap_data,
            "total_hits": sum(d.get("total_hits", 0) for d in self.heatmap_data.values()),
            "total_score": sum(d.get("total_score", 0) for d in self.heatmap_data.values()),
        }, indent=2)
    
    def get_consistency_score(self) -> float:
        """
        Calculate a consistency score (0.0-1.0).
        Higher = more consistent throws.
        """
        if not self.heatmap_data:
            return 0.0
        
        # Calculate standard deviation of hits per segment
        hits = [d.get("total_hits", 0) for d in self.heatmap_data.values()]
        
        if not hits or sum(hits) == 0:
            return 0.0
        
        avg_hits = sum(hits) / len(hits)
        variance = sum((h - avg_hits) ** 2 for h in hits) / len(hits)
        std_dev = variance ** 0.5
        
        # Normalize: 0 = very inconsistent, 1 = very consistent
        # Lower std dev = higher consistency
        max_std_dev = avg_hits * 2  # Arbitrary threshold
        consistency = max(0.0, 1.0 - (std_dev / max_std_dev))
        
        return min(1.0, consistency)
    
    def get_focus_segments(self, top_n: int = 3) -> List[Tuple[int, int]]:
        """Get the top N segments the player focuses on."""
        sorted_segs = sorted(
            [(seg, d.get("total_hits", 0)) for seg, d in self.heatmap_data.items()],
            key=lambda x: x[1],
            reverse=True
        )
        return sorted_segs[:top_n]
    
    def get_weak_segments(self, top_n: int = 3) -> List[Tuple[int, int]]:
        """Get the top N weakest segments."""
        sorted_segs = sorted(
            [(seg, d.get("total_hits", 0)) for seg, d in self.heatmap_data.items()],
            key=lambda x: x[1]
        )
        return sorted_segs[:top_n]


class HeatmapComparison:
    """Compare heatmaps between two players."""
    
    def __init__(self, player1_name: str, heatmap1: Dict, player2_name: str, heatmap2: Dict):
        self.player1_name = player1_name
        self.heatmap1 = heatmap1
        self.player2_name = player2_name
        self.heatmap2 = heatmap2
    
    def get_comparison_json(self) -> str:
        """Generate a comparison in JSON format."""
        comparison = {
            "player1": {
                "name": self.player1_name,
                "total_hits": sum(d.get("total_hits", 0) for d in self.heatmap1.values()),
                "top_segment": self._get_top_segment(self.heatmap1),
            },
            "player2": {
                "name": self.player2_name,
                "total_hits": sum(d.get("total_hits", 0) for d in self.heatmap2.values()),
                "top_segment": self._get_top_segment(self.heatmap2),
            },
        }
        return json.dumps(comparison, indent=2)
    
    @staticmethod
    def _get_top_segment(heatmap: Dict) -> int:
        """Get the top segment from a heatmap."""
        if not heatmap:
            return 0
        return max(heatmap.items(), key=lambda x: x[1].get("total_hits", 0))[0]
